language: r
cache: packages
sudo: false

repos:
    CRAN: https://cloud.r-project.org

r_packages:
    - lintr
    - covr

script:
    - R CMD build .

after_script:
    - Rscript -e 'lintr::lint_package()'
    - Rscript -e 'testthat::test_dir("Tests")'
    - Rscript -e 'cover::codecov()'
